// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmLJZcKeL3wGB9M0_-gw1vPM1OZyniAlE',
    appId: '1:158249219840:web:9a2535061d079233c1e5e5',
    messagingSenderId: '158249219840',
    projectId: 'e-project-ed6c9',
    authDomain: 'e-project-ed6c9.firebaseapp.com',
    storageBucket: 'e-project-ed6c9.firebasestorage.app',
    measurementId: 'G-F9R9D08887',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBODQ5Vx0sQQTDEuv2fmoBQgWi8H6XBkeY',
    appId: '1:158249219840:android:0d4681abbcf36a5ac1e5e5',
    messagingSenderId: '158249219840',
    projectId: 'e-project-ed6c9',
    storageBucket: 'e-project-ed6c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdIY9ADKfR0Z7-4P0bSxojatAvsc0kDc4',
    appId: '1:158249219840:ios:57589f66fede82c4c1e5e5',
    messagingSenderId: '158249219840',
    projectId: 'e-project-ed6c9',
    storageBucket: 'e-project-ed6c9.firebasestorage.app',
    iosClientId: '158249219840-rvrgir6mubfu2f2emhgercul06h7t2d9.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdIY9ADKfR0Z7-4P0bSxojatAvsc0kDc4',
    appId: '1:158249219840:ios:57589f66fede82c4c1e5e5',
    messagingSenderId: '158249219840',
    projectId: 'e-project-ed6c9',
    storageBucket: 'e-project-ed6c9.firebasestorage.app',
    iosClientId: '158249219840-rvrgir6mubfu2f2emhgercul06h7t2d9.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
